name = "prisma-cf-workers"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-10"
webpack_config = "webpack.config.js"
